(no-such-function 1 2 3)
(display 5)
(lambda (value) (+ value 10))
((lambda (value) (+ value 10)) 7)
(define f (lambda () 3))
(display (f))
(define fun-add (lambda (a b) (+ a b)))
(display (fun-add 7 50))
(define (mult10 x) (display x) (* x 10))
(display (mult10 38))
(display 5)
