;(+ 1 2)
;(+ 1 2 3)
;(display "qwe")
;(display '(a (b) c))
;(display '(a . #\$))
;(define a 4)
;(display a)
;(set! a 5)
;(display a)
;(dynamic e 3)
;(display e)
;(if #t 1 4)
;(if #f 3 2)
;(if #t 3)
;(if #f 5)
;(cond (#t 3) (#t 4))
;(cond (#t 3) (#f 4))
;(cond (#f 3) (#t 4))
;(cond (#f 3) (#f 4))
;(cond (#t 3) (#t 4) (else 5))
;(cond (#t 3) (#f 4) (else 5))
;(cond (#f 3) (#t 4) (else 5))
;(cond (#f 3) (#f 4) (else 5))
;334.3345
;(equal? 3 3)
;(equal? 3 4)
;(equal? 'a 'a)
;(equal? 'a 'b)
;(equal? '(a c) '(a c))
;(equal? '(a c) '(a b))
;(equal? '(a (d) c) '(a (d) c))
;(equal? '(a (d) c) '(a (a) c))
;(and)
;(and #t)
;(and #f)
;(and #t #t)
;(and #t #f)
;(and #f #t)
;(and #f #f)
;(and #t #t #t)
;(and #t #f #t)
; ttf tfff tf
(or)
(or #t)
(or #f)
(or #t #t)
(or #t #f)
(or #f #t)
(or #f #f)
(or #t #t #t)
(or #f #f #f)
; ftf tttf tf
